# Generated by Django 2.2.16 on 2022-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administator'), ('moderator', 'Moderator'), ('user', 'User')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]