# Generated by Django 2.2.16 on 2022-09-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220922_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administator'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
